sudo: false
dist: trusty
language: node_js

node_js:
  - "6"

addons:
  chrome: stable

install:
    - npm install

after_install:
  - npm rebuild node-sass

matrix:
  fast_finish: true

cache:
  directories:
    - "node_modules"

before_script:
  - npm rebuild node-sass
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
    - npm run ci
