version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
configuration: Release
platform: Any CPU
environment:
  website_name: IndependerStarter
  nodejs_version: "6.9.4"

install:
  - ps: Install-Product node $env:nodejs_version
  - ps: $env:path = $env:appdata + "\npm;" + $env:path
  - npm install

test_script:
  # Output useful info for debugging.
  - node --version && npm --version
  - node -e 'console.log(process.env);'
  # - cmd: npm test

cache:
  - node_modules -> package.json                                        # local npm modules

before_build:
  - dotnet restore
build:
  - npm run ci